import type { ContractPacketContext, ContractParty } from './types'
import { COMPANY_ADDRESS, COMPANY_NAME, COMPANY_EMAIL, COMPANY_REGISTRY } from './types'
import { buildContractPartyFullLabel, normalizeLineValue } from './utils'

export const buildGdprText = (context: ContractPacketContext): string =>
    [
        'W związku z wejściem w życie Rozporządzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych, oraz uchylenia dyrektywy 95/46/WE (dalej: „RODO”) informujemy Państwa, że Kancelaria przetwarza między innymi dane osobowe:',
        'a. klientów będących osobami fizycznymi;',
        'b. w przypadku klientów Kancelarii będących osobami prawnymi bądź jednostkami organizacyjnymi nieposiadającymi osobowości prawnej - dane osobowe osób uprawnionych do reprezentacji takich podmiotów, pracowników i współpracowników takich klientów;',
        'c. dostawców usług będących osobami fizycznymi, jak również pracowników i współpracowników dostawców usług;',
        'd. osób zgłaszających się do Kancelarii w celu uzyskania pomocy w zakresie doradztwa prawnego świadczonego przez kancelarię, jak również osób, których dane zostały uzyskane przy okazji świadczenia takich usług na rzecz klientów Kancelarii;',
        'e. osób współpracujących z Kancelarią w sposób stały bądź sporadyczny przy świadczeniu usług przez Kancelarię.',
        'W konsekwencji powyższego, poniżej podajemy Państwu istotne informacje dotyczące przetwarzania danych osobowych.',
        '',
        'ADMINISTRATOR DANYCH OSOBOWYCH',
        '',
        `Administratorem danych osobowych jest ${COMPANY_NAME} z siedzibą w Warszawie ${COMPANY_REGISTRY}.`,
        '',
        'DANE KONTAKTOWE ADMINISTRATORA',
        '',
        'Możecie się Państwo skontaktować z Kancelarią w jeden z następujących sposobów:',
        `a. e-mailowo: ${COMPANY_EMAIL};`,
        `b. w siedzibie Kancelarii: ${COMPANY_ADDRESS}.`,
        '',
        'CELE PRZETWARZANIA DANYCH, PODSTAWA PRAWNA ORAZ PRAWNIE UZASADNIONE INTERESY',
        '',
        'Informujemy, że Państwa dane osobowe będą przetwarzane tylko w sytuacji, gdy jest to niezbędne do:',
        'a. zawarcia i wykonania umowy, tj. na podstawie art. 6 ust. 1 lit. b RODO, w tym w szczególności umowy obsługi prawnej bądź umowy o świadczenie usług na rzecz Kancelarii przez dostawców takich usług;',
        'b. wypełnienia obowiązków prawnych ciążących na administratorze danych osobowych na podstawie art. 6 ust. 1 lit. c RODO, wynikających z prawa Unii lub prawa polskiego;',
        'c. do celów wynikających z prawnie uzasadnionych interesów realizowanych przez administratora lub stronę trzecią na podstawie art. 6 ust. 1 lit. f RODO, za które administrator uznaje w szczególności: dochodzenie, ustalenie i obronę przed roszczeniami, zapobieganie oszustwom, zapewnienie bezpieczeństwa środowiska teleinformatycznego, stosowanie systemów kontroli wewnętrznej, monitorowanie Kancelarii oraz rejestrowanie wejść i wyjść z Kancelarii, ustalanie konfliktów interesów i naruszeń etycznych w zakresie niezbędnym do przeciwdziałania nadużyciom, w celach archiwalnych i statystycznych, jak również świadczenie usług na rzecz klienta, w sytuacji, w których interes klienta jest nadrzędny wobec interesów, praw i wolności osoby, których dane dotyczą.',
        '',
        'KATEGORIE PRZETWARZANYCH DANYCH OSOBOWYCH',
        'Kancelaria przetwarza następujące kategorie danych osobowych:',
        'a. dane mające na celu potwierdzenie tożsamości takie jak imię i nazwisko, numer PESEL, numer i serię dowodu osobistego, datę urodzenia;',
        'b. dane kontaktowe, takie jak: numer telefonu, adres email, adres zamieszkania;',
        'c. dane identyfikacji podatkowej;',
        'd. dane dotyczące wykształcenia oraz doświadczenia zawodowego – jeśli jest to konieczne z punktu widzenia świadczonych usług;',
        'e. dane dotyczące sytuacji majątkowej i finansowej - jeśli jest to konieczne z punktu widzenia świadczonych usług;',
        'f. dane dotyczące działalności zawodowej, gospodarczej;',
        'g. dane dotyczące stanu cywilnego - jeśli jest to konieczne z punktu widzenia świadczonych usług;',
        'h. dane szczególnej kategorii, w tym w szczególności dane wizerunkowe, dane dotyczące stanu zdrowia, dane dotyczące karalności, dane biometryczne, dane dotyczące seksualności – jeśli jest to konieczne z punktu widzenia świadczonych usług.',
        'Ponadto Kancelaria może przetwarzać inne kategorie danych osobowych, o ile nie można zakwalifikować tych danych do żadnej ze wskazanych grup, a przetwarzanie jest dokonywane w celach określonych niniejszą informacją.',
        '',
        'KATEGORIE ODBIORCÓW DANYCH',
        'Odbiorcami danych mogą być podmioty z następujących kategorii:',
        'a. współpracujący z Kancelarią adwokaci, radcowie prawni, notariusze oraz inne podmioty świadczące usługi prawne i samodzielnie decydujące o celach i sposobach przetwarzania danych;',
        'b. podmioty upoważnione na podstawie obowiązujących przepisów prawa (w szczególności sądy i organy państwowe);',
        'c. biura informacji gospodarczej;',
        'd. podmioty świadczące usługi informatyczne oraz nowych technologii, płatnicze, księgowo-finansowe, audytorskie i kontrolne, windykacyjne, drukarskie, niszczenia dokumentów, pocztowe oraz kurierskie.',
        '',
        'PRZEKAZYWANIE DANYCH POZA EUROPEJSKI OBSZAR GOSPODARCZY',
        'Kancelaria zasadniczo nie przekazuje danych osobowych poza Europejski Obszar Gospodarczy. Kancelaria może jednak zlecać wykonanie określonych usług bądź zadań informatycznych usługodawcom mającym siedzibę poza Europejskim Obszarem Gospodarczym. W takim przypadku dane są przekazywane do państwa trzeciego, w stosunku do którego na podstawie decyzji Komisji Europejskiej stwierdzono odpowiedni stopień ochrony danych. W każdej chwili może Pan/Pani zażądać dalszych informacji i kopii odpowiednich zabezpieczeń.',
        '',
        'OKRES PRZECHOWYWANIA DANYCH',
        'Dane osobowe mogą być przechowywane przez Kancelarię przez następujące okresy przechowywania danych, zależne od charakteru danych osobowych oraz celu ich przetwarzania:',
        'a. celem wykonania umowy/umów – do momentu ich rozwiązania bądź wygaśnięcia, lub',
        'b. ustalenia, dochodzenia lub obrony przed roszczeniami – do momentu przedawnienia roszczeń bądź wniesienia sprzeciwu, lub',
        'c. celem wypełnienia ciążących na Kancelarii obowiązków prawnych – do momentu wygaśnięcia obowiązków wynikających z przepisów prawa.',
        '',
        'PRZYSŁUGUJĄCE PRAWA',
        '',
        'W związku z przetwarzaniem przez Kancelarię Państwa danych osobowych, przysługują Państwu następujące prawa:',
        'a. prawo dostępu do treści swoich danych osobowych, ich sprostowania i uzupełnienia, ograniczenia ich przetwarzania i usunięcia;',
        'b. prawo do przenoszenia danych osobowych, które zostały przez Panią przekazane Kancelarii, tj. prawo do ich otrzymania w ustrukturyzowanym powszechnym formacie oraz ich przesłania innemu administratorowi. Prawo to może zostać zrealizowane wyłącznie w przypadkach, gdy przetwarzanie odbywa się na podstawie zgody bądź umowy oraz o ile jest całkowicie zautomatyzowane;',
        'c. prawo wniesienia skargi do organu nadzorczego zajmującego się ochroną danych osobowych w przypadku uznania, iż przetwarzanie danych osobowych narusza RODO;',
        'd. o ile przetwarzanie danych odbywa się na podstawie zgody Pani, ma Pani możliwość cofnięcia zgody w dowolnym momencie, przy czym cofnięcie zgody pozostaje bez wpływu na zgodność z prawem przetwarzania danych, dokonanego na podstawie tej zgody przed jej cofnięciem;',
        'e. ma Pan/Pani możliwość wniesienia sprzeciwu wobec przetwarzania danych osobowych, o ile przetwarzanie to odbywa się w celach wynikających z prawnie uzasadnionych interesów realizowanych przez Administratora lub stronę trzecią, tj. na podstawie art. 6 ust. 1 lit. f RODO. Przyczyną takiego sprzeciwu musi być Pana/Pani szczególna sytuacja.',
        'Po otrzymaniu sprzeciwu przestaniemy przetwarzać Pana/Pani dane w powyższych celach, co do których wyraził Pan/Pani sprzeciw, chyba że wykażemy istnienie ważnych prawnie uzasadnionych podstaw do przetwarzania, nadrzędnych wobec Pani interesów, praw i wolności lub podstaw do ustalenia, dochodzenia lub obrony przed roszczeniami. Celem skorzystania z powyższych praw należy skontaktować się z Kancelarią. Dane kontaktowe zostały podane na wstępie niniejszej klauzuli informacyjnej.',
        '',
        'INFORMACJA DOTYCZĄCA WYMOGU LUB DOBROWOLNOŚCI PODANIA DANYCH OSOBOWYCH ORAZ KONSEKWENCJACH ICH NIEPODANIA',
        'W zakresie przetwarzania danych osobowych w celu, o którym mowa w lit. b powyżej, obowiązek podania danych jest wymogiem ustawowym; z kolei w przypadku przetwarzania danych w celach, o których mowa w lit. a i c, obowiązek podania danych jest wymogiem umownym – podanie danych osobowych we wszystkich celach, o których mowa powyżej, jest dobrowolne, jednak jest niezbędne do zawarcia i realizacji umowy z kancelarią.',
        '',
        `Oświadczam, że zapoznałem/am się z klauzulą informacyjną dotyczącą przetwarzania danych osobowych przez ${COMPANY_NAME} z siedzibą w Warszawie.`,
        `Dokument przekazano w związku z umową zawartą dnia ${normalizeLineValue(context.contractDate)} z klientem/klientami: ${buildContractPartyFullLabel(context.parties)}.`
    ].join('\n')

export const buildReceivablesAuthorizationText = (_context: ContractPacketContext, party: ContractParty): string =>
    [
        'Ja, niżej podpisana/podpisany',
        `Pani/Pan: ${normalizeLineValue(party.fullName)}`,
        `PESEL: ${normalizeLineValue(party.pesel)}`,
        `Adres: ${normalizeLineValue(party.address)}`,
        'niniejszym:',
        `upoważniam Kancelarię ${COMPANY_NAME}`,
        `(${COMPANY_REGISTRY})`,
        '',
        'do odbioru w moim imieniu i na moją rzecz od przedsiębiorstw przesyłowych, ich następców prawnych oraz innych podmiotów zobowiązanych wszelkich należności pieniężnych wypłaconych w postępowaniu przedsądowym, na mocy prawomocnego orzeczenia sądowego lub na mocy ugody.',
        'Upoważnienie obejmuje prawo do:',
        '    1. zaliczenia odebranej kwoty na poczet wynagrodzenia Kancelarii,',
        '    2. wystawienia pokwitowania odbioru należności w tym zakresie.',
        'Upoważnienie niniejsze:',
        '    • ma charakter szczególny,',
        '    • obowiązuje wyłącznie w zakresie i na zasadach określonych w Umowie,',
        'Klient oświadcza, że:',
        '    • rozumie treść i skutki niniejszego upoważnienia,',
        '    • zostało ono udzielone dobrowolnie,',
        '    • nie narusza jego prawa do informacji o dokonanych rozliczeniach.'
    ].join('\n')
